# Querying Available Data Sets

The US Census publishes dozens of data sets per year. They have published over
1,300 data sets in all via their API. Some, like 
the *American Community Survey: 5-Year Estimates: Data Tables*
are widely known and used, but there are plenty of other interesting and useful
data sets you might want to load.

`censusdis` supports querying avaialble data sets for a given year or for all time.

We have not loaded all variables for all data sets for all years, but 
`censusdis` should be able to.
If you encounter one it cannot load, please file and issue at 
https://github.com/vengroff/censusdis/issues and we will look into it.

In [1]:
# So we can run from within the censusdis project and find the packages we need.
import os
import sys

sys.path.append(
    os.path.join(os.path.abspath(os.path.join(os.path.curdir, os.path.pardir)))
)

## Imports and configuration

In [2]:
import censusdis.data as ced

## Data sets available for a given year

In [3]:
YEAR = 2020

In [4]:
df_datasets_for_year = ced.variables.all_data_sets(year=YEAR)

df_datasets_for_year

,YEAR,DATASET,TITLE,DESCRIPTION
0,2020,abscb,Economic Surveys: Annual Business Survey: Annu...,The Annual Business Survey (ABS) provides info...
1,2020,abscbo,Economic Surveys: Annual Business Survey: Annu...,The Annual Business Survey (ABS) provides info...
2,2020,abscs,Economic Surveys: Annual Business Survey: Annu...,The Annual Business Survey (ABS) provides info...
3,2020,absmcb,Economic Surveys: Annual Business Survey: Annu...,The Annual Business Survey (ABS) provides info...
4,2020,acs/acs5,American Community Survey: 5-Year Estimates: D...,The American Community Survey (ACS) is an ongo...
5,2020,acs/acs5/cprofile,American Community Survey: 5-Year Estimates: C...,The American Community Survey (ACS) is an ongo...
6,2020,acs/acs5/profile,American Community Survey: 5-Year Estimates: D...,The American Community Survey (ACS) is an ongo...
7,2020,acs/acs5/pums,2020 American Community Survey: 5-Year Estimat...,The American Community Survey (ACS) Public Use...
8,2020,acs/acs5/pumspr,2020 American Community Survey: 5-Year Estimat...,The Public Use Microdata Sample (PUMS) for Pue...
9,2020,acs/acs5/subject,American Community Survey: 5-Year Estimates: S...,The American Community Survey (ACS) is an ongo...
10,2020,cbp,Economic Surveys: Business Patterns: County Bu...,County Business Patterns (CBP) is an annual se...
11,2020,cps/arts/feb,Current Population Survey: Arts Benchmarking S...,ABS collects information about individual atte...
12,2020,cps/asec/mar,Current Population Survey Annual Social and Ec...,The Annual Social and Economic Supplement or M...
13,2020,cps/basic/apr,Current Population Survey: Basic Monthly,"To provide estimates of employment, unemployme..."
14,2020,cps/basic/aug,Current Population Survey: Basic Monthly,"To provide estimates of employment, unemployme..."
15,2020,cps/basic/dec,Current Population Survey: Basic Monthly,"To provide estimates of employment, unemployme..."
16,2020,cps/basic/feb,Current Population Survey: Basic Monthly,"To provide estimates of employment, unemployme..."
17,2020,cps/basic/jan,Current Population Survey: Basic Monthly,"To provide estimates of employment, unemployme..."
18,2020,cps/basic/jul,Current Population Survey: Basic Monthly,"To provide estimates of employment, unemployme..."
19,2020,cps/basic/jun,Current Population Survey: Basic Monthly,"To provide estimates of employment, unemployme..."
20,2020,cps/basic/mar,Current Population Survey: Basic Monthly,"To provide estimates of employment, unemployme..."
21,2020,cps/basic/may,Current Population Survey: Basic Monthly,"To provide estimates of employment, unemployme..."
22,2020,cps/basic/nov,Current Population Survey: Basic Monthly,"To provide estimates of employment, unemployme..."
23,2020,cps/basic/oct,Current Population Survey: Basic Monthly,"To provide estimates of employment, unemployme..."
24,2020,cps/basic/sep,Current Population Survey: Basic Monthly,"To provide estimates of employment, unemployme..."
25,2020,cps/dwjt/jan,"Current Population Survey: Displaced Worker, E...",Displaced Workers: Provides data on workers wh...
26,2020,cps/fertility/jun,Current Population Survey: Fertility Supplement,Provides data on the number of children that w...
27,2020,cps/foodsec/dec,Current Population Survey: Food Security Suppl...,Provides data that will measure hunger and foo...
28,2020,cps/school/oct,Current Population Survey: School Enrollment S...,Provides information on population 3 years old...
29,2020,cps/vets/aug,Current Population Survey: Veterans Supplement,Provides data for veterans of the United State...
30,2020,cps/voting/nov,Current Population Survey: Voting Supplement,Provides demographic information on persons wh...
31,2020,dec/dpas,Decennial Census of Island Areas: American Sam...,The U.S. Census Bureau conducts the Island Are...
32,2020,dec/dpgu,Decennial Census of Island Areas: Guam Demogra...,The U.S. Census Bureau conducts the Island Are...
33,2020,dec/dpmp,Decennial Census of Island Areas: Northern Mar...,The U.S. Census Bureau conducts the Island Are...
34,2020,dec/dpvi,Decennial Census of Island Areas: U.S. Virgin ...,The U.S. Census Bureau conducts the Island Are...
35,2020,dec/pes,Decennial Census: Decennial Post-Enumeration S...,Post-Enumeration Survey estimates of net cover...
36,2020,dec/pl,Decennial Census: Redistricting Data (PL 94-171),"Public Law 94-171, enacted in 1975, directs th..."
37,2020,dec/responserate,Decennial Census: Decennial Self-Response Rate,Daily Decennial Self-Response Rates
38,2020,pdb/blockgroup,Planning Database Block Group Level,"The PDB is a database of U.S. housing, demogra..."
39,2020,pdb/statecounty,2020 Planning Database - State and County Level,This is a one-time release of the Census Burea...
40,2020,pdb/tract,Planning Database: Tract Level,"The PDB is a database of U.S. housing, demogra..."

## Data sets available for all years

In [5]:
df_all_datasets = ced.variables.all_data_sets()

df_all_datasets

,YEAR,DATASET,TITLE,DESCRIPTION
0,1986.0,cbp,1986 County Business Patterns: Business Patterns,County Business Patterns (CBP) is an annual se...
1,1987.0,cbp,1987 County Business Patterns: Business Patterns,County Business Patterns (CBP) is an annual se...
2,1988.0,cbp,1988 County Business Patterns: Business Patterns,County Business Patterns (CBP) is an annual se...
3,1989.0,cbp,1989 County Business Patterns: Business Patterns,County Business Patterns (CBP) is an annual se...
4,1989.0,cps/basic/apr,Apr 1989 Current Population Survey: Basic Monthly,"To provide estimates of employment, unemployme..."
...,...,...,...,...
1317,NaN,timeseries/pseo/earnings,Post-Secondary Employment Outcomes (PSEO): Pos...,Post-Secondary Employment Outcomes (PSEO) are ...
1318,NaN,timeseries/pseo/flows,Post-Secondary Employment Outcomes (PSEO): Pos...,Post-Secondary Employment Outcomes (PSEO) are ...
1319,NaN,timeseries/qwi/rh,Time Series Longitudinal Employer-Household Dy...,The Quarterly Workforce Indicators (QWI) are a...
1320,NaN,timeseries/qwi/sa,Time Series Longitudinal Employer-Household Dy...,The Quarterly Workforce Indicators (QWI) are a...
1321,NaN,timeseries/qwi/se,Time Series Longitudinal Employer-Household Dy...,The Quarterly Workforce Indicators (QWI) are a...

## List the groups in a dataset

In [6]:
dataset = df_datasets_for_year.iloc[4]["DATASET"]
dataset

'acs/acs5'

In [7]:
df_groups = ced.variables.all_groups(dataset, YEAR)

df_groups

,DATASET,YEAR,GROUP,DESCRIPTION
0,acs/acs5,2020,B01001,SEX BY AGE
1,acs/acs5,2020,B01001A,SEX BY AGE (WHITE ALONE)
2,acs/acs5,2020,B01001B,SEX BY AGE (BLACK OR AFRICAN AMERICAN ALONE)
3,acs/acs5,2020,B01001C,SEX BY AGE (AMERICAN INDIAN AND ALASKA NATIVE ...
4,acs/acs5,2020,B01001D,SEX BY AGE (ASIAN ALONE)
...,...,...,...,...
1135,acs/acs5,2020,C27014,PUBLIC HEALTH INSURANCE BY WORK EXPERIENCE
1136,acs/acs5,2020,C27016,HEALTH INSURANCE COVERAGE STATUS BY RATIO OF I...
1137,acs/acs5,2020,C27017,PRIVATE HEALTH INSURANCE BY RATIO OF INCOME TO...
1138,acs/acs5,2020,C27018,PUBLIC HEALTH INSURANCE BY RATIO OF INCOME TO ...
1139,acs/acs5,2020,C27021,HEALTH INSURANCE COVERAGE STATUS BY LIVING AR...

## List the variables in a group

In [8]:
group = df_groups.iloc[-5]["GROUP"]
group

'C27014'

In [9]:
df_variables = ced.variables.all_variables(dataset, YEAR, group)
df_variables

,YEAR,DATASET,GROUP,VARIABLE,LABEL,SUGGESTED_WEIGHT,VALUES
0,2020,acs/acs5,C27014,C27014_001E,Estimate!!Total:,NaN,None
1,2020,acs/acs5,C27014,C27014_002E,"Estimate!!Total:!!Worked full-time, year-round:",NaN,None
2,2020,acs/acs5,C27014,C27014_003E,"Estimate!!Total:!!Worked full-time, year-round...",NaN,None
3,2020,acs/acs5,C27014,C27014_004E,"Estimate!!Total:!!Worked full-time, year-round...",NaN,None
4,2020,acs/acs5,C27014,C27014_005E,"Estimate!!Total:!!Worked less than full-time, ...",NaN,None
5,2020,acs/acs5,C27014,C27014_006E,"Estimate!!Total:!!Worked less than full-time, ...",NaN,None
6,2020,acs/acs5,C27014,C27014_007E,"Estimate!!Total:!!Worked less than full-time, ...",NaN,None
7,2020,acs/acs5,C27014,C27014_008E,Estimate!!Total:!!Did not work:,NaN,None
8,2020,acs/acs5,C27014,C27014_009E,Estimate!!Total:!!Did not work:!!With public c...,NaN,None
9,2020,acs/acs5,C27014,C27014_010E,Estimate!!Total:!!Did not work:!!No public cov...,NaN,None

## Show the variables in a tree

In [10]:
ced.variables.group_tree(dataset, YEAR, group)

+ Estimate
    + Total: (C27014_001E)
        + Worked full-time, year-round: (C27014_002E)
            + With public coverage (C27014_003E)
            + No public coverage (C27014_004E)
        + Worked less than full-time, year-round: (C27014_005E)
            + With public coverage (C27014_006E)
            + No public coverage (C27014_007E)
        + Did not work: (C27014_008E)
            + With public coverage (C27014_009E)
            + No public coverage (C27014_010E)

## List all the leaves of the tree

In [11]:
leaves = ced.variables.group_leaves(dataset, YEAR, group)
leaves

['C27014_003E',
 'C27014_004E',
 'C27014_006E',
 'C27014_007E',
 'C27014_009E',
 'C27014_010E']

## Query the data

In [12]:
# Note that these two are equivalent. Using `leaves_of_group=group`
# could have saved us needing to construct `leaves` with the
# separate call above.

df_download_variables = ced.download(dataset, YEAR, leaves, state="*")
df_download_leaves_of_group = ced.download(
    dataset, YEAR, leaves_of_group=group, state="*"
)

df_download_leaves_of_group.equals(df_download_variables)

True

In [13]:
df_download_variables

,STATE,C27014_003E,C27014_004E,C27014_006E,C27014_007E,C27014_009E,C27014_010E
0,42,282813,3936257,428403,1492576,691948,683856
1,06,1374376,10959296,1773518,4694829,2306967,2715925
2,54,54298,456747,74180,163977,177283,112574
3,49,32811,955292,48745,472159,75240,217961
4,36,682381,5703442,901892,2135736,1276372,1139733
5,11,25265,257881,30201,78979,48885,30775
6,02,23966,190562,32449,106897,34460,44862
7,12,401669,6212125,399329,2513817,961401,1674842
8,45,107049,1493945,108716,580082,276030,370390
9,38,14537,256412,16776,104423,19607,32869
10,23,25533,407962,41683,178827,77363,58090
11,13,168501,3314750,166185,1264296,462749,857110
12,01,75843,1423256,78067,540687,320987,406785
13,33,23957,461188,38029,182053,53264,66680
14,41,119163,1175171,198499,532910,234140,233120
15,56,8863,183814,10046,79873,17303,36047
16,04,209241,1980455,251539,758185,396259,479384
17,22,148697,1249862,173016,453971,363999,314243
18,18,131642,2055323,198159,809014,337807,386602
19,16,28632,499391,37380,245311,64417,114182
20,09,92423,1081766,154354,443137,168766,197937
21,15,33642,417542,43196,157676,58403,80596
22,17,288510,3980277,409366,1511031,581603,816258
23,25,235053,2122254,326100,878593,357411,315603
24,48,429774,9129322,392899,3507585,964519,2447273
25,30,31841,295037,45156,140213,47166,53451
26,31,29308,656923,31713,244400,50326,90420
27,39,303814,3472694,462996,1321470,661439,609880
28,08,161908,1816067,214518,726399,228801,316622
29,34,173745,2838870,243804,1099656,366326,593718
30,24,166291,1986115,190913,673236,257918,338402
31,51,163082,2750475,159265,1045318,313113,577403
32,50,21272,185998,32007,79282,34732,21750
33,37,179393,3137513,214270,1263978,517007,770802
34,05,91675,838456,99700,275666,237071,178118
35,53,187247,2253788,291772,960869,361407,456895
36,20,43783,944358,45237,369139,93556,169884
37,40,65805,1175836,64873,457040,179996,314931
38,55,115916,1907149,177397,727003,236847,260607
39,28,46154,832804,53174,319814,206865,243551
40,29,87163,1940917,110536,751474,278097,392648
41,26,251826,2796716,413718,1228631,644554,562436
42,44,30234,320975,43515,134701,64969,49605
43,27,152178,1813873,222561,705573,196156,219438
44,19,80034,1017463,108695,361520,125274,128039
45,35,97998,497507,111490,181157,170661,131417
46,32,77213,898084,94827,361572,153875,213596
47,10,25494,285568,36096,102394,52158,54952
48,72,121979,535502,208400,190812,609747,249120
49,21,145764,1217060,191290,434073,387212,231214
50,46,14846,287885,16505,109530,26141,40652
51,47,160642,2031150,166729,760774,398301,475430